{{- if .Values.adminKey.publicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "symposium.adminKeySecret" . }}
  labels:
    {{- include "symposium.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin_pub_{{ .Values.adminKey.handle }}.key: {{ .Values.adminKey.publicKey | quote }}
{{- end }}
