apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "symposium.name" . }}
  labels:
    {{- include "symposium.labels" . | nindent 4 }}
  {{- if .Values.storage.keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.storage.className }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
