from symposium_data.runtime import Settings

SERVICE_ENV = """\
# generated by start.sh
DATABASE_URL=postgresql://u:p@127.0.0.1:5432/symposium_data
S3_ENDPOINT=http://127.0.0.1:8333
S3_ACCESS_KEY=ak
S3_SECRET_KEY=sk=with=equals
SERVER_ID=6f1c
TOKEN_KEY_FILE=/apps/data/config/token_ed25519.pem
SHARE_SECRET=s
"""


def test_settings_read_service_env_and_operator_variables(tmp_path):
    path = tmp_path / "service.env"
    path.write_text(SERVICE_ENV)
    s = Settings(
        str(path),
        environ={
            "SYMPOSIUM_DATA_REGISTRATION": "open",
            "SYMPOSIUM_DATA_PUBLIC_BASE_URL": "https://data.example.org",
        },
    )
    assert s.database_url.startswith("postgresql://u:p@")
    assert s.s3_secret_key == "sk=with=equals"
    assert s.s3_bucket == "symposium-data"
    assert s.server_id == "6f1c"
    assert s.registration == "open"
    assert s.public_base_url == "https://data.example.org"


def test_registration_defaults_to_invite(tmp_path):
    path = tmp_path / "service.env"
    path.write_text(SERVICE_ENV)
    assert Settings(str(path), environ={}).registration == "invite"
